version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks: 
      my-network:
        ipv4_address: 172.19.0.100
  kafka:
    # build: .
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.19.0.101
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - zookeeper
    networks: 
      my-network:
        ipv4_address: 172.19.0.101
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks: 
      my-network:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
      - "4369:4369"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks: 
      my-network:

  config-service:
    image: kms199711/config-service:1.0
    ports:
      - "8888:8888"
    environment:
      spring.rabbitmq.host: rabbitmq
      spring.profiles.active: default
    depends_on: 
      - rabbitmq
    networks: 
      my-network:

  discovery-service:
    image: kms199711/discovery-service:1.0
    ports:
      - "8761:8761"
    environment:
      spring.cloud.config.uri: http://config-service:8888
    depends_on: 
      - config-service
    networks: 
      my-network:

  apigateway-service:
    image: kms199711/apigateway-service:1.0
    ports:
      - "80:8000"
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.rabbitmq.host: rabbitmq
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/
    depends_on: 
      - config-service
      - discovery-service
    networks: 
      my-network:

  mariadb:
    image: kms199711/my_mariadb:1.0
    ports:
      - "3306:3306"
    networks: 
      my-network:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks: 
      my-network:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /Users/minsungkim/monitoring_grafa/prometheus-2.43.0.darwin-amd64/prometheus.yml:/etc/prometheus/prometheus.yml
    networks: 
      my-network:

  grafana:
    image: grafana/grafana 
    ports:
      - "3000:3000"
    networks: 
      my-network:

  user-service:
    image: kms199711/user-service:1.0
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.base-url: http://zipkin:9411
      spring.redis.host: redis
      spring.redis.port: 6379
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/
      logging.file: /api-logs/users-ws.log
    depends_on: 
      - config-service
      - apigateway-service
    networks: 
      my-network:
        ipv4_address: 172.19.0.12

  resume-service:
    image: kms199711/resume-service:1.0
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.base-url: http://zipkin:9411
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/
      spring.datasource.url: jdbc:mariadb://mariadb:3306/mydb
      logging.file: /api-logs/orders-ws.log
    depends_on: 
      - apigateway-service
    networks: 
      my-network:
        ipv4_address: 172.19.0.13
  
  category-service:
    image: kms199711/category-service:1.0
    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.base-url: http://zipkin:9411
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/
      logging.file: /api-logs/catalogs-ws.log
    depends_on: 
      - apigateway-service
    networks: 
      my-network:
        ipv4_address: 172.19.0.14

networks: 
  my-network:
    external: true
    name: resume-network
